<div class="facet-group active-filters">
  <div class="title"><?=$this->transEsc('Remove Filters')?></div>
  <? foreach ($filterList as $field => $filters): ?>
    <? foreach ($filters as $i => $filter): ?>
      <?
        $index = isset($filter['field']) ? array_search($filter['field'], $collapsedFacets) : false;
        if ($index !== false) {
          unset($collapsedFacets[$index]); // Open if we have a match
        }
        if (isset($filter['specialType']) && $filter['specialType'] == 'keyword') {
          $removeLink = $this->currentPath() . $results->getUrlQuery()->replaceTerm($filter['value'], '');
        } else {
          $removeLink = $this->currentPath() . $results->getUrlQuery()->removeFacet($filter['field'], $filter['value'], $filter['operator']);
        }
        if ($filter['displayText'] == '[* TO *]') {
          $filter['displayText'] = $this->translate('filter_wildcard');
        }
      ?>
      <a class="facet" href="<?=$removeLink ?>" title="<?=$this->transEsc('clear_tag_filter') ?>">
        <span class="status"><i class="fa fa-times" aria-hidden="true"></i></span>
        <? if ($filter['operator'] == 'NOT'): ?><?=$this->transEsc('NOT') ?><? endif; ?>
        <? if ($filter['operator'] == 'OR' && $i > 0): ?><?=$this->transEsc('OR') ?><? endif; ?>
        <?php
            if ($field == 'new_arrivals'):
                //echo $filter['displayText'];
                $fromDate = mb_substr(trim(explode('TO', $filter['value'])[0]), 1);
                $toDate = mb_substr(trim(explode('TO', $filter['value'])[1]), 0, -1);
                //echo $fromDate;
                $diff = date_diff(new DateTime($toDate), new DateTime($fromDate))->days;
                if ($diff) {
                    switch ($diff) {
                        case '7':
                            $filter['displayText'] = 'arrivals_week';
                            break;
                        case '31':
                            $filter['displayText'] = 'arrivals_month';
                            break;
                        case '93':
                            $filter['displayText'] = 'arrivals_quarter';
                            break;
                        case '365':
                            $filter['displayText'] = 'arrivals_year';
                            break;
                        default:
                            # code...
                            break;
                    }
                }
                echo $this->transEsc($field) ?>: <?=$this->translate($this->escapeHtml($filter['displayText']));
            else:
                echo $this->transEsc($field) ?>: <?=$this->translate($this->escapeHtml($filter['displayText']));
            endif;
        ?>
      </a>
    <? endforeach; ?>
  <? endforeach; ?>
</div>
