<?php
    $cntFormats = count(array_unique($this->driver->getFormats()));
    $cntPrint = 0;
    foreach (array_unique($this->driver->getFormats()) as $format): 
        $cntPrint++;
        echo ($cntFormats == $cntPrint) 
            ? '<span class="format '.$this->record($this->driver)->getFormatClass($format) .'">'.$this->transEsc($format) .'</span>'
            : '<span class="format '.$this->record($this->driver)->getFormatClass($format) .'">'.$this->transEsc($format) .',&nbsp;</span>';
    endforeach;
?>