<?php 
    $status = $this->driver->getRecordStatus($this->driver->getUniqueId());
    if ($status) {
        switch($status) {
            case 'available':
                echo "<span class='status' style='color:#008000;'>".$this->transEsc('record-'.$status)."</span>&nbsp<span class='access-method' style='text-transform: lowercase;'>".$this->driver->getMethodOfAccess()[0]."</span>";
                break;
            case 'booked':
                "<span class='status' style='color:#ff9d00;'>".$this->transEsc('record-'.$status)."</span>";
                break;
            case 'busy':
                "<span class='status' style='color:#ff0000;'>".$this->transEsc('record-'.$status)."</span>";
                break;
            default:
                "<span class='status'>текст-заглушка</span>";
                break;
        }
    }
?>