<? $records = $this->cart()->getRecordDetails(); if (!empty($records)): ?>
  <hr/>
  <ul class="list-unstyled">
  <? foreach ($records as $i => $record): ?>
    <li>
      <div class="checkbox">
        <label>
          <?=$this->record($record)->getCheckbox('cart', false, true)?>
          <!--<a title="<?=$this->transEsc('View Record')?>" href="<?=$this->recordLink()->getUrl($record)?>" data-lightbox-ignore><?=$this->escapeHtml($record->getBreadcrumb())?></a>-->
	  <a title="<?=$this->transEsc('View Record')?>" href="<?=$this->recordLink()->getUrl($record)?>" data-lightbox-ignore><?=$this->escapeHtml($record->getTitle())?></a>
	  <?php if ($record->getPrimaryAuthor() != '') echo "<span>".$record->getPrimaryAuthor()."</span>";?>
        </label>
      </div>
    </li>
  <? endforeach; ?>
  </ul>
<? else: ?>
  <p class="alert alert-info"><?=$this->transEsc('bookbag_is_empty')?>.</p>
<? endif; ?>
