<? $records = $this->cart()->getRecordDetails(); if (!empty($records)): ?>
  <hr/>
  <ul class="list-unstyled">
  <? foreach ($records as $i => $record): ?>
    <li>
      <div class="checkbox">
        <label>
          <?=$this->record($record)->getCheckbox('cart')?>
          <!--<a title="<?=$this->transEsc('View Record')?>" href="<?=$this->recordLink()->getUrl($record)?>" data-lightbox-ignore><?=$this->escapeHtml($record->getBreadcrumb())?></a>-->
	  <a title="<?=$this->transEsc('View Record')?>" href="<?=$this->recordLink()->getUrl($record)?>" data-lightbox-ignore><?=$this->escapeHtml($record->getTitle())?></a>
	  <?php if ($record->getPrimaryAuthor() != '') echo " (Автор: ".$record->getPrimaryAuthor().")";?> 
	<?php 
		//$arr = get_class_methods($record);
		//print_r($arr);

		//echo "<br/><br/><br/>";
		//print_r($record->getPrimaryAuthor());
		//echo $record->getPrimaryAuthor();
	?>
        </label>
      </div>
    </li>
  <? endforeach; ?>
  </ul>
<? else: ?>
  <p class="alert alert-info"><?=$this->transEsc('bookbag_is_empty')?>.</p>
<? endif; ?>
