<?/*
  $transParams = [
    '%%start%%' => $this->localizedNumber($this->results->getStartRecord()),
    '%%end%%'   => $this->localizedNumber($this->results->getEndRecord()),
    '%%total%%' => $this->localizedNumber($this->recordTotal),
    '%%lookfor%%' => $this->escapeHtml($this->lookfor)
  ];
?>
<? if (!isset($this->skipTotalCount)): ?>
  <? $showingResults = $this->translate('showing_results_of_html', $transParams); ?>
<? else: ?>
  <? $showingResults = $this->translate('showing_results_html', $transParams); ?>
<? endif; ?>
<? if (isset($this->overrideSearchHeading)): ?>
  <? $showingResults .= ' ' . $this->overrideSearchHeading; ?>
<? elseif ($this->params->getSearchType() == 'basic'): ?>
  <? if (!isset($this->skipTotalCount)): ?>
    <? $showingResults = $this->translate('showing_results_of_for_html', $transParams); ?>
  <? else: ?>
    <? $showingResults = $this->translate('showing_results_for_html', $transParams); ?>
  <? endif; ?>
<? endif; ?>
<? $this->layout()->srmessage = $showingResults; ?>
<? if ($qtime = $this->results->getQuerySpeed()): ?>
  <?=$showingResults; ?>, <?=$this->transEsc('query time')?>: <?=$this->localizedNumber($qtime, 2).$this->transEsc('seconds_abbrev')?>
<? else: ?>
  <?=$showingResults; ?>
<? endif; */?>
<div class="search_info_wrapper">
    <!-- Place alert here -->    
    <!--<div class="search_info_you">Вы искали</div>-->
    <!--<div class="search_info_text"><? echo $this->escapeHtml($this->lookfor) ?></div>-->
    <!--<div class="search_info_advanced"><a href="/Search/Advanced">Расширенный поиск</a></div>-->
    <? if ($this->layout()->searchbox !== false): ?>
        <div class="search container navbar">
            <div class="search_info_advanced"><a href="/Search/Advanced">Расширенный поиск</a></div>
            <nav class="nav searchbox hidden-print">
                <?=$this->layout()->searchbox ?>
            </nav>
        </div>
    <? endif; ?>
    <div class="search-tools-wrapper">
    <div class="search_info_found desktop_version">Найдено документов: <? echo $this->localizedNumber($this->results->getStartRecord()) ?>&mdash;<? echo $this->localizedNumber($this->results->getEndRecord()) ?> из <? echo $this->localizedNumber($this->recordTotal) ?>.</div>
    <div class="search_info_found mobile_version">Найдено: <? echo $this->localizedNumber($this->results->getStartRecord()) ?>&mdash;<? echo $this->localizedNumber($this->results->getEndRecord()) ?> из <? echo $this->localizedNumber($this->recordTotal) ?>.</div>


    <? if (($recordTotal = $this->results->getResultTotal()) > 0): // only display these at very top if we have results ?>
        <? endif; ?>
    <? if ($recordTotal > 0): ?>
    <div class="search-controls">

    <?/*=$this->render('search/controls/limit.phtml')*/?>
    <?=$this->render('search/controls/sort.phtml')?>
    <?/*=$this->render('search/controls/view.phtml')*/?>
    </div>
    <? endif; ?>
</div>


</div>
