<?= $this->doctype('HTML5') ?>
<html lang="<?= $this->layout()->userLang ?>">
    <head>
        <!-- Yandex.Metrika counter -->
        <script type="text/javascript" >
            (function (d, w, c) {
                (w[c] = w[c] || []).push(function() {
                    try {
                        w.yaCounter49410553 = new Ya.Metrika2({
                            id:49410553,
                            clickmap:true,
                            trackLinks:true,
                            accurateTrackBounce:true,
                            webvisor:true
                        });
                    } catch(e) { }
                });

                var n = d.getElementsByTagName("script")[0],
                    s = d.createElement("script"),
                    f = function () { n.parentNode.insertBefore(s, n); };
                s.type = "text/javascript";
                s.async = true;
                s.src = "https://mc.yandex.ru/metrika/tag.js";

                if (w.opera == "[object Opera]") {
                    d.addEventListener("DOMContentLoaded", f, false);
                } else { f(); }
            })(document, window, "yandex_metrika_callbacks2");
        </script>
        <noscript><div><img src="https://mc.yandex.ru/watch/49410553" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
        <!-- /Yandex.Metrika counter -->
        <!-- Yandex.Metrika counter -->
        <script type="text/javascript" >
            (function (d, w, c) {
                (w[c] = w[c] || []).push(function() {
                    try {
                        w.yaCounter49410553 = new Ya.Metrika2({
                            id:49410553,
                            clickmap:true,
                            trackLinks:true,
                            accurateTrackBounce:true,
                            webvisor:true
                        });
                    } catch(e) { }
                });

                var n = d.getElementsByTagName("script")[0],
                    s = d.createElement("script"),
                    f = function () { n.parentNode.insertBefore(s, n); };
                s.type = "text/javascript";
                s.async = true;
                s.src = "https://mc.yandex.ru/metrika/tag.js";

                if (w.opera == "[object Opera]") {
                    d.addEventListener("DOMContentLoaded", f, false);
                } else { f(); }
            })(document, window, "yandex_metrika_callbacks2");
        </script>
        <noscript><div><img src="https://mc.yandex.ru/watch/49410553" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
        <!-- /Yandex.Metrika counter -->
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-74053759-9"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag() {
                dataLayer.push(arguments);
            }
            gtag('js', new Date());
            gtag('config', 'UA-74053759-9');
        </script>
        <meta http-equiv="Cache-Control" content="private">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
        <?= $this->headMeta() ?>
        <?= $this->headTitle() ?>
        <?= $this->headLink() ?>
        <?= $this->headStyle() ?>
        <link rel="shortcut icon" type="image/png" href="/themes/libfl/images/favicon/favicon.png" sizes="16x16">
        <link rel="shortcut icon" type="image/png" href="/themes/libfl/images/favicon/favicon2x.png" sizes="32x32">
        <?
        // Session keep-alive
        if ($this->KeepAlive()) {
            $this->headScript()->appendScript('var keepAliveInterval = ' . $this->KeepAlive());
            $this->headScript()->appendFile("keep_alive.js");
        }
        ?>
        <?= $this->headScript() ?>
    </head>
    <body>
        <?=$this->layout()->content ?>
    </body>
    <!--<script src="/themes/libfl/js/moment-with-locales.min.js"></script>
    <script src="/themes/libfl/js/moment-timezone-with-data-2010-2020.min.js"></script>-->
    <!--<script src="/themes/libfl/js/jquery-ui.all.min.js"></script>-->
    <!--<script src="/themes/libfl/js/jquery.form.js"></script>
    <script src="/themes/libfl/js/main.js?_=1499547038"></script>-->
</html>
