<?=$this->doctype('HTML5')?>
<html lang="<?=$this->layout()->userLang?>">
<head>
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter49410553 = new Ya.Metrika2({
                        id:49410553,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true,
                        webvisor:true
                    });
                } catch(e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = "https://mc.yandex.ru/metrika/tag.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks2");
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/49410553" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-74053759-9"></script>
  <script>
  window.dataLayer = window.dataLayer || [];
  function gtag() {
    dataLayer.push(arguments);
  }
  gtag('js', new Date());

  gtag('config', 'UA-74053759-9');
  </script>
  <?$this->headThemeResources()?>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
  <?=$this->headMeta()?>
  <?=$this->headTitle()?>
  <?
      // Set up OpenSearch link:
  $this->headLink(
    [
    'href' => $this->url('search-opensearch') . '?method=describe',
    'type' => 'application/opensearchdescription+xml',
    'title' => $this->transEsc("Library Catalog Search"),
    'rel' => 'search'
    ]
    );
    ?>
    <!-- RTL styling -->
    <? if ($this->layout()->rtl) {
      $this->headLink()->appendStylesheet('vendor/bootstrap-rtl.min.css');
    } ?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
    <link rel="shortcut icon" type="image/png" href="/themes/bootstrap3/images/favicon/favicon.png" sizes="16x16">
    <link rel="shortcut icon" type="image/png" href="/themes/bootstrap3/images/favicon/favicon2x.png" sizes="32x32">
    <?
    if (!isset($this->renderingError)) {
        // Add translation strings
      $this->jsTranslations()->addStrings(
        [
        'add_tag_success' => 'add_tag_success',
        'bulk_email_success' => 'bulk_email_success',
        'bulk_noitems_advice' => 'bulk_noitems_advice',
        'bulk_save_success' => 'bulk_save_success',
        'close' => 'close',
        'collection_empty' => 'collection_empty',
        'error_occurred' => 'An error has occurred',
        'go_to_list' => 'go_to_list',
        'libphonenumber_invalid' => 'libphonenumber_invalid',
        'libphonenumber_invalidcountry' => 'libphonenumber_invalidcountry',
        'libphonenumber_invalidregion' => 'libphonenumber_invalidregion',
        'libphonenumber_notanumber' => 'libphonenumber_notanumber',
        'libphonenumber_toolong' => 'libphonenumber_toolong',
        'libphonenumber_tooshort' => 'libphonenumber_tooshort',
        'libphonenumber_tooshortidd' => 'libphonenumber_tooshortidd',
        'loading' => 'Loading',
        'more' => 'more',
        'number_thousands_separator' => [
        'number_thousands_separator', null, ','
        ],
        'sms_success' => 'sms_success'
        ]
        );
        // Add libphonenumber.js strings
$this->jsTranslations()->addStrings(
  [
  "Phone number invalid" => 'libphonenumber_invalid',
  "Invalid country calling code" => 'libphonenumber_invalidcountry',
  "Invalid region code" => 'libphonenumber_invalidregion',
  "The string supplied did not seem to be a phone number" => 'libphonenumber_notanumber',
  "The string supplied is too long to be a phone number" => 'libphonenumber_toolong',
  "The string supplied is too short to be a phone number" => 'libphonenumber_tooshort',
  "Phone number too short after IDD" => 'libphonenumber_tooshortidd'
  ]
  );
        // Deal with cart stuff:
$cart = $this->cart();
if ($cart->isActive()) {
  $this->headScript()->appendFile("vendor/cookies.js");
  $this->headScript()->appendFile("cart.js");
  $domain = $cart->getCookieDomain();
  if (!empty($domain)) {
    $this->headScript()->appendScript(
      'VuFind.cart.setDomain("' . $domain . '");'
      );
  }
  $cookiePath = $cart->getCookiePath();
  if (!empty($cookiePath)) {
    $this->headScript()->appendScript(
      'VuFind.cart.setCookiePath("' . $cookiePath . '");'
      );
  }
  $this->jsTranslations()->addStrings(
    [
    'addBookBag' => 'Add to Book Bag',
    'bookbagFull' => 'bookbag_full_msg',
    'bookbagMax' => $cart->getMaxSize(),
    'bookbagStatusFull' => 'bookbag_full',
    'confirmDelete' => 'confirm_delete',
    'confirmEmpty' => 'bookbag_confirm_empty',
    'itemsAddBag' => 'items_added_to_bookbag',
    'itemsInBag' => 'items_already_in_bookbag',
    'removeBookBag' => 'Remove from Book Bag',
    'viewBookBag' => 'View Book Bag'
    ]
    );
}
$this->headScript()->appendScript(
  'var userIsLoggedIn = ' . ($this->auth()->isLoggedIn() ? 'true' : 'false') . ';'
  );
}

      // Session keep-alive
if ($this->KeepAlive()) {
  $this->headScript()->appendScript('var keepAliveInterval = '
    . $this->KeepAlive());
  $this->headScript()->appendFile("keep_alive.js");
}
?>
<?
$root = rtrim($this->url('home'), '/');
$translations = $this->jsTranslations()->getJSON();
$dsb = DEFAULT_SEARCH_BACKEND;
$setupJS = <<<JS
VuFind.path = '{$root}';
VuFind.defaultSearchBackend = '{$dsb}';
VuFind.addTranslations({$translations});
JS;
$this->headScript()->appendScript($setupJS);
?>
<?=$this->headScript()?>
<!--<link href="/themes/bootprint3/css/libfl.css?_=1499547038" rel="stylesheet" type="text/css">-->
<!--<link href="/themes/libfl/css/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" type="text/css">-->
</head>
<!--<body class="template-dir-<?=$this->templateDir?> template-name-<?=$this->templateName?> <?=$this->layoutClass('offcanvas-row')?><? if ($this->layout()->rtl): ?> rtl<? endif; ?>">-->
<body class="template-dir-<?=$this->templateDir?> template-name-<?=$this->templateName?> offcanvas offcanvas-right flip <? if ($this->layout()->rtl): ?> rtl<? endif; ?>">

  <div id="layout_wrapper">

    <div class="infobar desktop_version">
      <div class="content-wrap">

        <div class="infobar__link left">
          <span><?=$this->transEsc("Let's be friends")?></span>
        </div>

        <div class="infobar__link left">
          <a href="https://vk.com/public59877134" class="social-btn social-btn_vk" target="_blank"></a>
          <a href="https://www.facebook.com/LIBFL/" class="social-btn social-btn_fb" target="_blank"></a>
          <a href="https://www.instagram.com/libfl/" class="social-btn social-btn_ig" target="_blank"></a>
          <a href="https://www.youtube.com/channel/UCyK_Z9yBQCcFzUZePsR5W4w" class="social-btn social-btn_yt" target="_blank"></a>
        </div>

        <div class="right">
          <a href="https://libfl.ru/ru/item/svedeniya-ob-organizacii-osushchestvlyayushchey-obrazovatelnuyu-deyatelnost" class="link infobar__link_academy"><?=$this->transEsc("Information about the organization engaged in educational activities")?></a>
        </div>

      </div>
    </div>

    <nav>

      <div id="mobile_menu_wrapper" class="mobile_version">
        <a href="/" class="logo_wrapper"><img src="/themes/libfl/images/svg/breve-icon.svg" alt=""></a>
        <a href="https://oauth.libfl.ru/" class="oauth_logo"></a>
        <button type="button" class="hamburger hamburger--squeeze">
          <span class="hamburger-box"><span class="hamburger-inner"></span></span>
        </button>
      </div>

      <div id="nav" class="clear">
        <div id="nav2">
          <div class="content-wrap">
            <div class="search_plug mobile_version">
              <input id="mobile_search" name="search" type="search" placeholder="Поиск по каталогу" value="">
            </div>
            <ul class="menu header__menu">
              <li class="menu__item">
                <a href="/" class="link menu__link"><?=$this->transEsc("Catalogue")?></a>
              </li>
              <li class="menu__item">
                <a href="https://libfl.ru/ru/news/uhodim-v-onlayn-lekcii-i-vebinary-ne-vyhodya-iz-doma" class="link menu__link">Онлайн-мероприятия</a>
              </li>
              <li class="menu__item">
                <a href="https://libfl.ru/ru/item/novosti-biblioteki" class="link menu__link"><?=$this->transEsc("Context")?></a></li>
              <li class="menu__item">
                <a href="https://libfl.ru/ru/item/about" class="link menu__link"><?=$this->transEsc("About Library")?></a>
              </li>
              <div class="header-menu__links" style="margin-left:auto;">
                <a class="become-member desktop_version" href="https://oauth.libfl.ru/" style="margin-left:30px"><?=$this->transEsc("Log in")?></a>
                <a class="become-member desktop_version js-become-member"><?=$this->transEsc("Become a user")?></a>
                <a class="switch-language" style="background: url(/images/svg/lang-en.svg) center no-repeat" href="/en"></a>
              </div>
            </ul>

            <div class="quick_links_wrapper mobile_version">
              <div class="quick_links mobile_version">
                <a href="/ru/item/contacts"><?=$this->transEsc("Contact")?></a>
                <br>
                <div class="closing-time"><?=$this->transEsc("Сегодня Иностранка не работает")?></div>
              </div>
              <div class="grey_quick_links">
                <a href="/ru/department/akademiya-rudomino">Академия Рудомино</a>
                <br>
                <a href="/static/online_resources"><?=$this->transEsc("Online resourses")?></a>
                <br>
                <a href="/ru/item/projects"><?=$this->transEsc("Special projects")?></a>
              </div>
              <div class="educational_institution">
                <a href="https://libfl.ru/ru/item/svedeniya-ob-organizacii-osushchestvlyayushchey-obrazovatelnuyu-deyatelnost">Сведения об организации, осуществляющей образовательную&nbsp;деятельность</a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div id="fixed_menu" class="desktop_version">
        <div class="fixed_menu_wrapper">
          <a href="http://libfl.ru/" class="fixed_logo"></a>

          <div class="content-wrap">
            <ul class="menu header__menu">
              <li class="menu__item">
                <a href="/" class="link menu__link"><?=$this->transEsc("Catalogue")?></a>
              </li>
              <!--
              <li class="menu__item">
                <a href="https://libfl.ru/ru/news/uhodim-v-onlayn-lekcii-i-vebinary-ne-vyhodya-iz-doma" class="link menu__link">Онлайн-мероприятия</a>
              </li>
              -->
              <li class="menu__item">
                <a href="http://libfl.ru/ru/item/novosti-biblioteki" class="link menu__link"><?=$this->transEsc("Context")?></a>
              </li>
              <li class="menu__item">
                <a href="http://libfl.ru/ru/item/about" class="link menu__link"><?=$this->transEsc("About Library")?></a>
              </li>
              <div class="header-menu__links" style="margin-left:auto;">
                <a class="become-member desktop_version" href="https://oauth.libfl.ru/" style="margin-left:30px">Войти</a>
                <a class="become-member desktop_version js-become-member">Стать читателем</a>
                <a class="switch-language" style="background: url(/images/svg/lang-en.svg) center no-repeat" href="/en"></a>
              </div>
            </ul>
          </div>

        </div>
      </div>

    </nav>

    <? // Set up the search box -- there are three possible cases:
      // 1. No search box was set; we should default to the normal box
      // 2. It was set to false; we should display nothing
      // 3. It is set to a custom string; we should display the provided version
      // Set up default search box if no data was provided from the template;
      // this covers case 1.  Cases 2 and 3 are then covered by logic below.
    if (!isset($this->layout()->searchbox)) {
      $this->layout()->searchbox = $this->render('search/searchbox.phtml');
    }
    ?>

    <header class="header">
      <div id="header">
        <div class="content-wrap clear">

          <a href="http://libfl.ru/" class="logo_wrapper desktop_version">
            <img id="random" src="" alt="">
          </a>

          <div class="quick-links desktop_version">
            <div class="quick-links__group">
              <a href="http://libfl.ru/static/online_resources" class="link quick-links__item"><?=$this->transEsc("Online resourses")?></a>
              <br>
              <a href="" class="link quick-links__item" id="random-department"></a>
              <br>
              <a href="https://readymag.com/u3137742749/1704431/" class="link quick-links__item">Information for foreign partners</a>
              <br>
              <a href="http://libfl.ru/ru/item/contacts" class="link quick-links__item"><?=$this->transEsc("Contact")?></a>
              <br>
              <a href="http://libfl.ru/ru/hours" class="closing-time"><?=$this->transEsc("Open until")?> </a>
            </div>
          </div>

          <div id="search_wrapper" class="vf_search_wrapper catalogue">

            <span class="search_switch"><?=$this->transEsc("Search")?> <b>по каталогу&nbsp;</b></span>
            <a href="/Search/Results?lookfor=&amp;type=AllFields" class="full-index"><?=$this->transEsc("Over 1 528 000 Books")?></a>
            <div class="vf_search_form desktop_version">
              <input id="search" name="search" type="text" value="">
              <img src="/themes/libfl/images/svg/options.svg">

              <div class="vf_search_select site_search">
                <div data-text="Поиск по сайту" data-action="" class="vf_search_option"><?=$this->transEsc("website")?></div>
                <div data-text="Поиск по мероприятиям" data-action="events" class="vf_search_option"><?=$this->transEsc("events")?></div>
                <div data-text="Поиск по статьям" data-action="articles" class="vf_search_option"><?=$this->transEsc("articles")?></div>
                <div data-text="Поиск по документам" data-action="documents" class="vf_search_option"><?=$this->transEsc("documents")?></div>
                <div data-text="Поиск по подборкам" data-action="books_collections" class="vf_search_option"><?=$this->transEsc("collections")?></div>
              </div>
              <div class="vf_search_select catalogue_search">
                <div data-text="Поиск по каталогу" data-action="" class="vf_search_option"><?=$this->transEsc("catalogue")?></div>
                <div data-text="Поиск по автору" data-action="author" class="vf_search_option"><?=$this->transEsc("author")?></div>
                <div data-text="Поиск по названию" data-action="title" class="vf_search_option"><?=$this->transEsc("title")?></div>
                <div data-text="Поиск по предметной области" data-action="subject" class="vf_search_option"><?=$this->transEsc("subject")?></div>
                <div data-text="Поиск по ISBN/ISNN" data-action="isbn" class="vf_search_option">ISBN/ISSN</div><a href="http://catalog.libfl.ru/Search/Advanced" class="advanced_search" target="_blank"><?=$this->transEsc("Advanced search")?></a>
              </div>
            </div>

          </div>

          <div class="wisemen_block desktop_version" id="rudomino">
            <img class="random-quote__image" src="/themes/libfl/images/wisemen/rudomino.png" alt="120 лет Маргарите Ивановне Рудомино" title="120 лет Маргарите Ивановне Рудомино">
            <a class="random-quote" href="http://press-libfl.tilda.ws/rudomino" target="_blank">
                <div class="random-quote__digit">120
                    <small> лет</small>
                </div>
                <div class="random-quote__small">Маргарите Ивановне<br>Рудомино</div>
            </a>
            <clear></clear>
          </div>

          <div id="random_quote1" style="display:none;" class="wisemen_block desktop_version">
            <img class="random-quote__image" src="/themes/libfl/images/wisemen/marquez.png" alt="Габриэль Гарсиа Маркез" title="Габриэль Гарсиа Маркез расставит все точки над и и а.">
            <div class="random-quote">
              <span class="random-quote__text"><b>Gabriel García Márquez<br>will dot the í's and á's.</b></span>
            </div>
            <clear></clear>
          </div>

          <div id="random_quote2" style="display:none;" class="wisemen_block desktop_version">
            <img class="random-quote__image" src="/themes/libfl/images/wisemen/plato.png" alt="Платон" title="Вуаля! Теперь я понимаю Платона.">
            <div class="random-quote">
              <span class="random-quote__text"><b>Voilà!<br>Plato is not Greek for you.</b></span>
            </div>
            <clear></clear>
          </div>

          <div id="random_quote3" style="display:none;" class="wisemen_block desktop_version">
            <img class="random-quote__image" src="/themes/libfl/images/wisemen/capek.png" alt="Карел Чапек" title="Дочитали книгу Карела Чапека? Поставьте сверху галочку.">
            <div class="random-quote">
              <span class="random-quote__text"><b>Just finished Karel Čapek's<br>book? Put a tick above.</b></span>
            </div>
            <clear></clear>
          </div>

          <div id="random_quote4" style="display:none;" class="wisemen_block desktop_version">
            <img class="random-quote__image" src="/themes/libfl/images/wisemen/sartr.png" alt="Жан-Поль Сартр" title="Потерял смысл жизни? Попробуй французских экзистенциалистов.">
            <div class="random-quote">
              <span class="random-quote__text"><b>Lost your raison d'être?<br>Try French existentialists.</b></span>
            </div>
            <clear></clear>
          </div>

          </div>
      </div>
    </header>

              <div class="hidden-print">
                <? if (isset($this->layout()->srmessage)): // message for benefit of screen-reader users ?>
                <span class="sr-only"><?=$this->layout()->srmessage ?></span>
              <? endif; ?>
              <a class="sr-only" href="#content"><?=$this->transEsc("Skip to content") ?></a>
              <?=$this->render('header.phtml')?>
            </div>
            <div class="breadcrumbs">
                <div class="content-wrap">
                    <a href="#" onclick="history.back(); return false;" class="btn breadcrumb-btn"></a>

                    <? if((!isset($this->layout()->showBreadcrumbs) || $this->layout()->showBreadcrumbs == true)
                      && !empty($this->layout()->breadcrumbs)
                      && $this->layout()->breadcrumbs !== false
                      ): ?>
                        <ul class="breadcrumb hidden-print">
                            <li><a href="/">Поиск</a></li>
                            <? if(is_array($this->layout()->breadcrumbs)): ?>
                            <? if(count($this->layout()->breadcrumbs) > 1): ?>
                            <?=$this->render('breadcrumbs/multi.phtml', [
                              'parents' => $this->layout()->breadcrumbs,
                              'title'   => $this->layout()->title,
                              'from'    => $this->layout()->from
                              ]) ?>
                            <? else: ?>
                            <?=$this->render('breadcrumbs/default.phtml', [
                              'parents' => $this->layout()->breadcrumbs,
                              'title'   => $this->layout()->title
                              ]) ?>
                            <? endif; ?>
                          <? else: ?>
                          <?=$this->layout()->breadcrumbs ?>
                          <? endif; ?>
                        </ul>
                    <? else: ?>
                        <ul class="breadcrumb hidden-print">
                            <li><a href="/">Поиск</a></li>
                        </ul>
                    <? endif; ?>

                    <!-- -->
                    <? $cart = $this->cart(); if ($cart->isActive()): ?>
                    <div id="cartSummary">
                      <a id="cartItems" data-lightbox title="<?=$this->transEsc("View Book Bag")?>" href="<?=$this->url('cart-home')?>">
                        <img src='/themes/libfl/images/svg/book-cart.svg' class='bookbag-full'><span class="cart_text"><?=$this->transEsc("My Books")?></span>  <span class="quantity"><?=count($cart->getItems())?></span>
                        <span class="full<?=!$cart->isFull() ? ' hidden' : '' ?>">(<?=$this->transEsc("bookbag_full") ?>)</span>
                      </a>
                    </div>
                    <? endif; ?>
                    <!-- -->

                </div>
            </div>
<div role="main" class="main">
<div id="content" class="container">
          <?=$this->layout()->content ?>
        </div>
      </div>

      <?=$this->render('footer.phtml')?>
    </div>
    <!-- MODAL IN CASE WE NEED ONE -->
    <div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
          <div class="modal-body"><?=$this->transEsc("Loading") ?>...</div>
        </div>
      </div>
    </div>
    <div class="offcanvas-toggle" data-toggle="offcanvas"><i class="fa" title="<?=$this->transEsc("sidebar_expand") ?>"></i></div>
    <div class="offcanvas-overlay" data-toggle="offcanvas"></div>
    <?=$this->googleanalytics()?>
    <?=$this->piwik()?>
    <? if ($this->recaptcha()->active()): ?>
    <?=$this->inlineScript(\Zend\View\Helper\HeadScript::FILE, "https://www.google.com/recaptcha/api.js?onload=recaptchaOnLoad&render=explicit&hl=" . $this->layout()->userLang, 'SET')?>
  <? endif; ?>
  <!-- Begin Me-Talk {literal} --> <script type='text/javascript'> (function(d, w, m) { window.supportAPIMethod = m; var s = d.createElement('script'); s.type ='text/javascript'; s.id = 'supportScript'; s.charset = 'utf-8'; s.async = true; var id = '83d66cc8637fc0056e8995dfec63b74d'; s.src = '//me-talk.ru/support/support.js?h='+id; var sc = d.getElementsByTagName('script')[0]; w[m] = w[m] || function() { (w[m].q = w[m].q || []).push(arguments); }; if (sc) sc.parentNode.insertBefore(s, sc); else d.documentElement.firstChild.appendChild(s); })(document, window, 'MeTalk'); </script> <!-- {/literal} End Me-Talk -->
</body>
<script src="/themes/libfl/js/moment-with-locales.min.js"></script>
<script src="/themes/libfl/js/moment-timezone-with-data-2010-2020.min.js"></script>
<!--<script src="/themes/libfl/js/jquery-ui.all.min.js"></script>-->
<script src="/themes/libfl/js/jquery.form.js"></script>
<script src="/themes/libfl/js/main.js?_=1499547038"></script>
<!--<script src="/themes/libfl/js/bootstrap-datepicker.min.js"></script>
<script src="/themes/libfl/js/bootstrap-datepicker.ru.min.js"></script>-->
<script src="/themes/libfl/js/moment-with-locales.min.js"></script>
</html>
