<!-- Button trigger modal -->
<!--<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
        Посмотреть демо
</button>-->
<a href="" data-toggle="modal" data-target="#order-info">This book is not available for order...</a>

<!-- Modal -->
<div class="modal fade" id="order-info" tabindex="-1" role="dialog" aria-labelledby="orderInfo" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Как заказать эту книгу?</h4>
      </div>
      <div class="modal-body">
        Информация о том, где и как можно заказать эту книгу!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>
