<? $this->headLink()->appendStylesheet('EDS.css'); ?>
<?
    $items = $this->driver->getItems();
    $dbLabel = $this->driver->getDbLabel();
    $thumb = $this->driver->getThumbnail('medium');
    $pubType = $this->driver->getPubType();
    $customLinks = $this->driver->getCustomLinks();
    $accessLevel = $this->driver->getAccessLevel();
    $restrictedView = empty($accessLevel) ? false : true;
?>
<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
   <!--<div class="media-body">
    <? /* if ($thumb): ?>
        <img src="<?=$this->escapeHtmlAttr($thumb)?>" class="recordcover" alt="<?=$this->transEsc('Cover Image')?>"/>
    <? else: ?>
        <!--<span class="recordcover pt-icon pt-<?=$this->driver->getPubTypeId()?>"></span>-->
    <? endif; */ ?>
    <? /* if ($pubType): ?>
        <p><?=$this->transEsc($pubType)?></p>
    <? endif; */ ?>
  </div>-->
  <div class="media-body info-col">
    <? if ($pubType): ?>
        <span class="EDS-source"><?=$this->transEsc($pubType)?></span>
    <? endif; ?>

    <h3 property="name"><?=$this->driver->getTitle()?></h3>
    <?
        foreach($items as $item):
            if ('Ab' == $item['Group']) {
                echo '<p>'.$item['Data'].'</p>';
            }
        endforeach;
    ?>
    <div class="ebsco-note">
      Просмотр в EDS временно доступен только из помещения библиотеки
      <span>Ведутся работы по обеспечению удаленного доступа авторизованных читателей</span>
    </div>
    <div class="external-links">
      <? $pLink = $this->driver->getPLink();
          if($pLink): ?>
        <span>
          <a href="<?=$this->escapeHtmlAttr($pLink)?>" target="_blank">
            <?=$this->transEsc('Просмотр в EDS')?>
          </a>
        </span>
      <? endif; ?>
      <? $pdfLink = $this->driver->getPdfLink();
          if ($pdfLink): ?>
        <span>
          <a href="<?=$pdfLink?>" class="fulltext">
            <?=$this->transEsc('PDF')?>
          </a>
        </span>
      <? endif; ?>
      <? if ($this->driver->hasHTMLFullTextAvailable()): ?>
        <span>
          <a href="<?=$this->recordLink()->getUrl($this->driver, 'fulltext')?>#html" class="fulltext">
            <?=$this->transEsc('Текст')?>
          </a>
        </span>
      <? endif; ?>

        <div class="external-links__readme">
            <a href="" class="">Как получить доступ?</a>
            <br>
            <a href="http://libfl.ru/static/online_resources" target="_blank" class="">Об Online-ресурсах</a>
        </div>
    </div>

    <table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
      <? foreach ($items as $key => $item): ?>
        <? if (!empty($item['Data']) && 'Ab' != $item['Group']): ?>
        <tr>
          <th><?=$this->transEsc($item['Label'])?></th>
          <td><?=$this->driver->linkUrls($item['Data'])?></td>
        </tr>
        <? endif; ?>
      <? endforeach; ?>

      <? if ($dbLabel): ?>
        <tr>
          <th><?=$this->transEsc('Database')?></th>
          <td><?=$this->escapeHtml($dbLabel)?></td>
        </tr>
      <? endif; ?>
    </table>

    <? if ($this->driver->hasHTMLFullTextAvailable() && !$restrictedView):
      $fullText = $this->driver->getHtmlFullText();?>
        <div id="html">
            <?=$fullText?>
        </div>
    <? elseif ($this->driver->hasHTMLFullTextAvailable() && $restrictedView): ?>
        <div class="ebsco-warning" id="html">
            <?=$this->transEsc('Full text is not displayed to guests')?>
            <span><a class="login" href="<?=$this->url('myresearch-home')?>" rel="nofollow"><?=$this->transEsc('Login for full access')?></a></span>
        <div>
    <? endif; ?>

    <div class="resultItemLine4 custom-links">
        <? $customLinks = array_merge($this->driver->getFTCustomLinks(), $this->driver->getCustomLinks());
        if (!empty($customLinks)): ?>
          <? foreach ($customLinks as $customLink): ?>
          <? $url = isset($customLink['Url']) ? $customLink['Url'] : '';
              $mot = isset($customLink['MouseOverText'])? $customLink['MouseOverText'] : '';
              $icon = isset ($customLink['Icon']) ? $customLink['Icon'] : '';
              $name = isset($customLink['Text']) ? $customLink['Text'] : '';
          ?>
          <span>
            <a href="<?=$this->escapeHtmlAttr($url)?>" target="_blank" title="<?=$this->escapeHtmlAttr($mot)?>" class="custom-link">
              <? if ($icon): ?><img src="<?=$this->escapeHtmlAttr($icon)?>" /> <? endif; ?><?=$this->escapeHtml($name)?>
            </a>
          </span>
          <? endforeach; ?>
        <? endif; ?>
    </div>

  </div>

  <div class="media-right info-col">
      <? if ($thumb): ?>
          <img src="<?=$this->escapeHtmlAttr($thumb)?>" class="recordcover" alt="<?=$this->transEsc('Cover Image')?>"/>
      <? else: ?>
          <!--<span class="recordcover pt-icon pt-<?=$this->driver->getPubTypeId()?>"></span>-->
      <? endif; ?>
    </div>
</div>
