<footer>
    <div id="footer">
        <div class="content_big">
            <div class="footer_columns">
                <div class="footer_column_left footer_left">
                    <div class="footer_logo">
                      <a><img src="/themes/bootstrap3/images/svg/tilde-icon.svg"></a>
                    </div>
                    <ul id="footer_menu">
                        <li>
                          <a href="http://libfl.ru/ru/item/catalogue"><?=$this->transEsc("Catalogue")?></a>
                        </li>
                        <li>
                          <a href="https://libfl.ru/ru/events"><?=$this->transEsc("Events")?></a>
                        </li>
                        <li>
                          <a href="http://libfl.ru/ru/item/novosti-biblioteki"><?=$this->transEsc("News")?></a>
                        </li>
                        <li>
                          <a href="https://libfl.ru/ru/departments">Департаменты</a>
                        </li>
                        <li>
                          <a href="http://libfl.ru/ru/item/about"><?=$this->transEsc("About Library")?></a>
                        </li>
                    </ul>
                    <div class="footer_social_wrapper">
                        <div class="footer_list">
                            <div class="footer_social_header"><?=$this->transEsc("Join us")?></div>
                            <li>
                              <a href="https://vk.com/public59877134" target="_blank"><img style="width: 12px; margin-right: .8em;" src="/themes/bootstrap3/images/svg/vk-grey-icon.svg"><span><?=$this->transEsc("VK")?></span></a>
                            </li>
                            <li>
                              <a href="https://www.facebook.com/LIBFL.RU/" target="_blank"><img style="width: 12px; margin-right: .8em;" src="/themes/bootstrap3/images/svg/fb-grey-icon.svg"><span>Facebook</span></a>
                            </li>
                            <li>
                              <a href="https://www.instagram.com/libfl/" target="_blank"><img style="width: 12px; margin-right: .8em;" src="/themes/bootstrap3/images/svg/in-grey-icon.svg"><span>Instagram</span></a>
                            </li>
                            <li>
                              <a href="https://www.youtube.com/channel/UCyK_Z9yBQCcFzUZePsR5W4w" target="_blank"><img style="width: 12px; margin-right: .8em;" src="/themes/bootstrap3/images/svg/yt-grey-icon.svg"><span>YouTube</span></a>
                            </li>
                        </div>
                    </div>
                    <div class="clear"></div>
                    <div class="footer_list_wrapper">
                        <ul class="footer_list">
                            <li>
                              <a href="http://libfl.ru/ru/item/contacts"><?=$this->transEsc("Contact")?></a>
                            </li>
                            <li>
                              <a href="http://libfl.ru/ru/item/pravila-biblioteki"><?=$this->transEsc("Library Rules")?></a>
                            </li>
                            <li>
                              <a href="http://libfl.ru/ru/item/istoriya-biblioteki"><?=$this->transEsc("Library History")?></a>
                            </li>
                            <li>
                              <a href="http://libfl.ru/ru/item/uslugi-biblioteki"><?=$this->transEsc("Services")?></a>
                            </li>
                            <li>
                              <a href="https://libfl.ru/ru/item/vakansii-biblioteki-inostrannoy-literatury"><?=$this->transEsc("Vacant positions")?></a>
                            </li>
                            <li>
                              <a href="http://libfl.ru/ru/item/projects"><?=$this->transEsc("Special projects")?></a>
                            </li>
                            <li>
                              <a href="http://libfl.ru/ru/item/awards"><?=$this->transEsc("Awards")?></a>
                            </li>
                        </ul>
                        <ul class="footer_list">
                            <li>
                              <a href="http://libfl.ru/ru/item/official-documents"><?=$this->transEsc("Official documents")?></a>
                            </li>
                            <li>
                              <a href="http://libfl.ru/ru/item/antikorrupcionnye-dokumenty"><?=$this->transEsc("Anti-corruption documents")?></a>
                            </li>
                            <li>
                              <a href="http://libfl.ru/ru/item/protivodeystvie-extremizmy"><?=$this->transEsc("Countering Extremism")?></a>
                            </li>
                            <li>
                              <a href="http://libfl.ru/ru/item/council"><?=$this->transEsc("International boards of trustees")?></a>
                            </li>
                            <li>
                              <a href="http://libfl.ru/ru/item/science-council"><?=$this->transEsc("Academic board")?></a>
                            </li>
                            <li>
                              <a href="http://libfl.ru/ru/item/departments"><?=$this->transEsc("Corporate documents")?></a>
                            </li>
                            <li>
                              <a href="http://libfl.ru/ru/item/partners"><?=$this->transEsc("Partners")?></a>
                            </li>
                        </ul>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="footer_column">
                  <span class="footer_header"><?=$this->transEsc("Address")?>:</span>
                  <br>
                  <span class="work_time"><?=$this->transEsc("Nikoloyamskaya Street 1, Moscow 109240")?> <a target="_blank" href="https://maps.yandex.ru/213/moscow/?utm_source=geoblock_maps_moscow&amp;text=109189%2C%20%D0%B3.%20%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0%2C%20%D1%83%D0%BB.%20%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%BE%D1%8F%D0%BC%D1%81%D0%BA%D0%B0%D1%8F%2C%20%D0%B4.%201&amp;sll=37.620393%2C55.753960&amp;sspn=1.852570%2C0.629645&amp;ol=geo&amp;ouri=ymapsbm1%3A%2F%2Fgeo%3Fll%3D37.648%252C55.748%26spn%3D0.001%252C0.001%26text%3D%25D0%25A0%25D0%25BE%25D1%2581%25D1%2581%25D0%25B8%25D1%258F%252C%2520%25D0%259C%25D0%25BE%25D1%2581%25D0%25BA%25D0%25B2%25D0%25B0%252C%2520%25D0%259D%25D0%25B8%25D0%25BA%25D0%25BE%25D0%25BB%25D0%25BE%25D1%258F%25D0%25BC%25D1%2581%25D0%25BA%25D0%25B0%25D1%258F%2520%25D1%2583%25D0%25BB%25D0%25B8%25D1%2586%25D0%25B0%252C%25201&amp;ll=37.648133%2C55.748234&amp;z=16"><?=$this->transEsc("View Map")?></a></span>
                  <br>
                  <br>
                  <span class="footer_header"><?=$this->transEsc("Reader Registration Office")?>:</span>
                  <br>
                  <span class="work_time">+7 (495) 915-35-03</span>
                  <br>
                  <br>
                  <span class="footer_header"><?=$this->transEsc("Information Service")?>:</span>
                  <br>
                  <span class="work_time">+7 (495) 915–36–41</span>
                  <br>
                  <br>
                  <span class="footer_header"><?=$this->transEsc("Book Store")?>:</span>
                  <br>
                  <span class="work_time">+7 (495) 915–35–17</span>
                  <br>
                  <br>
                  <span class="footer_header"><?=$this->transEsc("Opening Hours")?>:</span>
                  <br>
                  <!--
                  <span class="work_time"><?=$this->transEsc("On weekdays - from 11.00 to 21.00")?></span>
                  <br>
                  <span class="work_time"><?=$this->transEsc("On holidays and Saturdays - from 11.00 to 19.00")?></span>
                  <br>
                  <span class="work_time"><?=$this->transEsc("Sunday is a day off.")?></span>
                  -->
                  <span class="work_time">В будние дни — с 12.00 до 21.00</span>
                  <br>
                  <span class="work_time">Суббота — с 12.00 до 20.00</span>
                  <br>
                  <span class="work_time">С 15:00 до 16:00 Библиотека закрыта на дезинфекцию</span>
                  <br>
                  <span class="work_time">Воскресенье — библиотека не работает</span>
                  <br>
                  <br>
                  <span class="footer_header"><?=$this->transEsc("Admission and registration of users close 30 minutes prior to Library's closing time.")?></span>
                </div>
            </div>
            <div class="clear"></div>
            <div class="footer_copy">
                <div class="content_big">
                    <div class="footer_copy_text"><?=$this->transEsc("© 2013 All-Russian State Library for Foreign Literature named after M.I.Rudomino.The entire content of this website is protected by copyright and other intellectual property rights and is the property of the respective copyright holders or the LIBRARY.")?></div>
                    <span class="footer_year">© 2019</span>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>

    <div id="popup-wrapper" style="display: none;">

      <div id='popup-readme' class='popup-box'>
          <div class='popup-close'></div>
          <div class='popup-text'></div>
      </div>

      <div id="popup-reader" class="popup-box" style="display: none;">
          <div class="popup-close"></div>
          <div class="decoration-left"></div>
          <div class="decoration-right"></div>
          <div class="modal">
             <div class="modal_parts">
                <div class="modal_part">
                   <div class="modal_title">Читательский билет</div>
                   <div class="modal_subtitle">Читательский билет выдается на пять лет c последующей перерегистрацией</div>
                   <ul class="modal_list">
                      <li class="yesto">посещение <a href="https://libfl.ru/ru/events" target="_blank">мероприятий</a> Иностранки</li>
                      <li class="yesto">заказ книг на дом/для работы в читальном зале из книгохранения (только для прописанных в Москве и МО)</li>
                      <li class="yesto">чтение книг из открытого доступа Иностранки</li>
                      <li class="yesto">работа в читальных залах Иностранки</li>
                      <li class="yesto">работа с&nbsp;<a href="https://libfl.ru/static/online_resources" target="_blank">онлайн-ресурсами&nbsp;</a>в читальных залах на оборудовании Иностранки</li>
                      <li class="yesto">бесплатный доступ к&nbsp;<a href="https://libfl.ru/static/litres/" target="_blank">ЛитРес.Библиотека</a></li>
                      <li class="yesto">доступ к бесплатному wi-fi</li>
                   </ul>
                </div>
                <div class="modal_part">
                   <div class="modal_title">Гостевой пропуск</div>
                   <div class="modal_subtitle">Разовый, на выходе из библиотеки вы сдаете его</div>
                   <ul class="modal_list">
                      <li class="yesto">посещение <a href="https://libfl.ru/ru/events" target="_blank">мероприятий</a> Иностранки</li>
                      <li class="noto">заказ книг на дом/для работы в читальном зале из книгохранения (только для прописанных в Москве и МО)</li>
                      <li class="yesto">чтение книг из открытого доступа Иностранки</li>
                      <li class="yesto">работа в читальных залах Иностранки</li>
                      <li class="noto">работа с&nbsp;<a href="https://libfl.ru/static/online_resources" target="_blank">онлайн-ресурсами&nbsp;</a>в читальных залах на оборудовании Иностранки</li>
                      <li class="noto">бесплатный доступ к&nbsp;<a href="https://libfl.ru/static/litres/" target="_blank">ЛитРес:Библиотека</a></li>
                      <li class="yesto">доступ к бесплатному wi-fi</li>
                   </ul>
                </div>
             </div>
             <div class="modal_cta">Как и где получить?</div>
             <div class="modal_parts">
                <div class="modal_part">
                   <div class="modal_title">Читательский билет</div>
                   <ol class="modal_list">
                      <li>Заполнить электронную анкету на первом этаже Иностранки или&nbsp;<a href="https://oauth.libfl.ru/signup" target="_blank">зарегистрироваться на сайте.</a></li>
                      <li>Подойти к сотрудникам на стойке регистрации с документом, подтверждающим вашу личность.<span>Паспорт, водительские права или др.</span></li>
                      <li>Получить читательский билет</li>
                   </ol>
                </div>
                <div class="modal_part">
                   <div class="modal_title">Гостевой пропуск</div>
                   <ol class="modal_list">
                      <li>Обратиться к сотрудникам на стойке регистрации, показать документ с фотографией, подтверждающий вашу личность.<span>Паспорт, водительские права или др.</span></li>
                   </ol>
                </div>
             </div>
             <div class="modal_welcome"><span>Welcome!</span><a href="https://oauth.libfl.ru/signup" target="_blank" class="btn btn_blue">Регистрация</a></div>
             <div class="modal_rules"><a href="https://libfl.ru/ru/about/pravila-biblioteki" target="_blank" class="link">Полная версия правил Библиотеки</a></div>
          </div>
       </div>
    </div>

</footer>
