<footer>
    <div id="footer">
        <div class="content_big">
            <div class="footer_columns">
                <div class="footer_column_left footer_left">
                    <div class="footer_logo"><a><img src="/vufind/themes/bootstrap3/images/svg/tilde-icon.svg"></a></div>
                    <ul id="footer_menu">
                        <li><a href="/ru/item/catalogue">Каталоги</a></li>
                        <li><a href="/ru/item/events">Мероприятия</a></li>
                        <li><a href="/ru/item/centers">Национальные центры</a></li>
                        <li><a href="/ru/item/about">О библиотеке</a></li>
                    </ul>
                    <div class="clear"></div>
                    <div class="footer_list_wrapper">
                        <ul class="footer_list">
                            <li><a href="/ru/item/contacts">Контактная информация</a></li>
                            <li><a href="/ru/item/pravila-biblioteki">Правила библиотеки</a></li>
                            <li><a href="/ru/item/istoriya-biblioteki">История библиотеки</a></li>
                            <li><a href="/ru/item/uslugi-biblioteki">Услуги</a></li>
                            <li><a href="/ru/item/novosti-biblioteki">Новости</a></li>
                            <li><a href="/ru/item/projects">Проекты</a></li>
                            <li><a href="/ru/item/awards">Премии</a></li>
                        </ul>
                        <ul style="margin-left: 60px;" class="footer_list">
                            <li><a href="/ru/item/official-documents">Официальные документы</a></li>
                            <li><a href="/ru/item/antikorrupcionnye-dokumenty">Антикоррупционные документы</a></li>
                            <li><a href="/ru/item/protivodeystvie-extremizmy">Противодействие экстримизму</a></li>
                            <li><a href="/ru/item/council">Международный попечительский совет</a></li>
                            <li><a href="/ru/item/science-council">Ученый совет</a></li>
                            <li><a href="/ru/item/departments">Организационная структура</a></li>
                            <li><a href="/ru/item/partners">Партнеры</a></li>
                        </ul>
                    </div>
                    <div class="clear">								</div>
                </div>
                <div class="footer_column"><span class="footer_header">Адрес:</span><br><span class="work_time">109189, г. Москва, ул. Николоямская, д. 1 <a target="_blank" href="https://maps.yandex.ru/213/moscow/?utm_source=geoblock_maps_moscow&amp;text=109189%2C%20%D0%B3.%20%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0%2C%20%D1%83%D0%BB.%20%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%BE%D1%8F%D0%BC%D1%81%D0%BA%D0%B0%D1%8F%2C%20%D0%B4.%201&amp;sll=37.620393%2C55.753960&amp;sspn=1.852570%2C0.629645&amp;ol=geo&amp;ouri=ymapsbm1%3A%2F%2Fgeo%3Fll%3D37.648%252C55.748%26spn%3D0.001%252C0.001%26text%3D%25D0%25A0%25D0%25BE%25D1%2581%25D1%2581%25D0%25B8%25D1%258F%252C%2520%25D0%259C%25D0%25BE%25D1%2581%25D0%25BA%25D0%25B2%25D0%25B0%252C%2520%25D0%259D%25D0%25B8%25D0%25BA%25D0%25BE%25D0%25BB%25D0%25BE%25D1%258F%25D0%25BC%25D1%2581%25D0%25BA%25D0%25B0%25D1%258F%2520%25D1%2583%25D0%25BB%25D0%25B8%25D1%2586%25D0%25B0%252C%25201&amp;ll=37.648133%2C55.748234&amp;z=16">Посмотреть на карте</a></span><br><br>
                    <!--a.work_time(href='/' + lang + '/item/contacts#scheme_anchor')=__("Схема библиотеки")-->
                    <!--br-->
                    <!--br--><span class="footer_header">Телефон:</span><br><span class="work_time">+7 (495) 915–36–41</span><br><br><span class="footer_header">Справочно-библиографические консультации:</span><br><span class="work_time">+7 (495) 915–36–36</span><br><br><span class="footer_header">Часы работы:</span><br><span class="work_time">В будние дни — с 11.00 до 21.00</span><br><span class="work_time">В предпраздничные, субботние и воскресные дни — с 11.00 до 19.00</span><br><span class="work_time">Последний четверг каждого месяца — санитарный день.</span><br><br><span class="footer_header">Запись читателей и вход их в библиотеку завершается за полчаса до окончания работы.</span>
                </div>
            </div>
            <div class="clear"></div>
            <div class="footer_copy">
                <div class="content_big">
                    <div class="footer_copy_text">© 2013 Федеральное государственное бюджетное учреждение культуры «Всероссийская государственная библиотека иностранной литературы имени М.И.Рудомино». Вся информация, представленная на сайте охраняется авторским правом и другими правами на интеллектуальную собственность и является собственностью соответствующих правообладателей или БИБЛИОТЕКИ.</div>
                    <!--a(href="https://metrika.yandex.ru/stat/?id=35488675&amp;from=informer", target="_blank", rel="nofollow", style='float: right;')img(src="https://informer.yandex.ru/informer/35488675/3_1_FFFFFFFF_EFEFEFFF_0_pageviews", style="width:88px; height:31px; border:0;", alt="Яндекс.Метрика", title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)", onclick="try{Ya.Metrika.informer({i:this,id:35488675,lang:'ru'});return false}catch(e){}")
                    --><span class="footer_year">© 2017</span>
                    <!--.footer_banner
                    a(href='http://quality.mkrf.ru/mark/?orgid=0373100000308', target='_blank')
                        img(src='/static/mkrf_controlquality.png', alt='')
                        | Оценка качества услуг
                        br
                        | учреждений культуры

                    -->
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
    <div id="popup_wrapper">
        <div class="mobile_close"></div>
        <div id="popup_book" class="popup_box">
            <div class="popup_close"></div>
            <div class="popup_text"><img src="/images/!book_example.png" alt="" class="popup_book_image">
                <div class="popup_book_info">
                    <div class="collection_book_author"></div>
                    <div class="collection_book_title"></div>
                    <div class="collection_book_label"></div>
                    <div class="clear"></div>
                    <div class="collection_book_place_wrapper">
                        <div class="collection_book_place"></div>
                        <div class="collection_book_readinghall">Доступно в читальном зале</div>
                    </div>
                    <div class="collection_book_description"></div>
                    <div class="collection_book_cite"></div>
                    <div class="collection_book_review"></div>
                    <div class="collection_book_bibliog_desc"></div><a href="#" target="_blank" class="collection_book_download">Скачать</a>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div id="popup_reader" class="popup_box">
            <div class="popup_close"></div>
            <div class="reader_left_text"> <b>Шаг 1</b><br><br>Для оформления читательского билета необходимо (самостоятельно или с помощью библиотекаря) пройти электронную регистрацию в центральном вестибюле на 1-м этаже библиотеки.<br><br>Вы также можете зарегистрироваться&nbsp;<a href="http://opac.libfl.ru/WebReaderT/(S(dl5ctyvv3ojvcj55epr3i1jn))/Default.aspx">online</a>.</div>
            <div class="reader_splitter"></div>
            <div class="reader_right_text"> <b>Шаг 2</b><br><br>Для завершения процедуры регистрации необходимо предоставить один из документов:<br>&mdash; паспорт;<br>&mdash; водительское удостоверение РФ.<br><br>Для несовершеннолетних в возрасте до 14 лет&nbsp;&mdash; свидетельство о рождении и паспорт сопровождающего.<br><br>Подробности смотрите в п.2&nbsp;<a href="http://libfl.ru/ru/item/pravila-biblioteki">Правил пользования Библиотекой иностранной литературы</a>.<br><br>Запись новых читателей завершается за полчаса до окончания работы библиотеки.</div>
        </div>
    </div>
</footer>
