<?php
// Set page title.
    $this->headTitle($this->translate('tabAccess') . ': ' . $this->driver->getBreadcrumb());

    $formatter = $this->recordDataFormatter();
    $getExemplars = $formatter->getData($driver, $formatter->getDefaults('libfl_exemplar'));

    if (isset($getExemplars['Exemplar']['value']) && !empty($getExemplars['Exemplar']['value'])) {
        $getExemplarsData = json_decode(htmlspecialchars_decode($getExemplars['Exemplar']['value']));
    }

    $fields = $getExemplarsData[0];
    $exemplars = json_decode($getExemplarsData[1][0]);
    $accessMethods = $this->driver->getMethodOfAccess();
    $getAccessMethod = (string) $this->driver->getMethodOfAccess()[0];
    $accessMethod = (!empty($getAccessMethod)) ? strtolower($getAccessMethod) : '';

    $remoteAccess = array_uintersect($accessMethods, array('4002'), "strcasecmp");
    $printOnDemandAccess = array_uintersect($accessMethods, array('4004'), "strcasecmp");
    $takeHomeAccess = array_uintersect($accessMethods, array('4001'), "strcasecmp");
    $libraryAccess = array_uintersect($accessMethods, array('4000','4006','4003'), "strcasecmp");
    $askEmployeeAccess = array_uintersect($accessMethods, array('4005'), "strcasecmp");
    //$unknownAccessTab = array_uintersect($accessMethods, array('4999'), "strcasecmp");

    if (!empty($exemplars)) {
        $newExemplars = array();
        foreach ($exemplars as $num=>$exemplar) {
            $newExemplars[$exemplar->exemplar_access.'.'.$exemplar->exemplar_location][$num] = array(
                'exemplar_id' => $exemplar->exemplar_id,
                'exemplar_location' => $exemplar->exemplar_location,
                'exemplar_rack_location' => $exemplar->exemplar_rack_location,
                'exemplar_placing_cipher' => $exemplar->exemplar_placing_cipher,
                'exemplar_inventory_number' => $exemplar->exemplar_inventory_number,
                'exemplar_inv_note' => $exemplar->exemplar_inv_note,
                'exemplar_hyperlink' => $exemplar->exemplar_hyperlink,
            );
        }
        print_r($exemplars);


        echo '<pre>';
        print_r($newExemplars);
        echo '</pre>';
        echo $accessMethod;

        // Удаленный доступ
        if (is_array($remoteAccess) && !empty($remoteAccess)) {
            echo "<h2><i class='fa fa-laptop' style='margin: 0px 5px 0px 0px;'></i>".$this->transEsc('access_remoteAccess')."</h2>";
            foreach ($newExemplars as $access=>$exemplar):
                $accessCodes = explode('.', $access);
                $accessCode = $accessCodes[0];
                $locationCode = $accessCodes[1];
                if ($accessExemplars = array_uintersect($accessCodes, array('1001','1002','1004','1008'),"strcasecmp")) {
                    echo '<div id="group_'.$access.'" class="exemplar" style="padding: 0px 0px 0px 26px;">';
                    //echo '<h3 style="font-weight:bold;"><i class="fa fa-book" style="margin: 0px 5px 0px 0px;"></i>'.$this->translate($accessCode."_group").'</h3>';
                    echo '<table class="table table-striped" summary="'.$this->transEsc('Exemplars').'" style="margin-bottom:40px;">';
                    $exemplarID = NULL;
                    $exemplar_carrier = NULl;
                    $group_inv_number = NULL;
                    $group_exemplars_id = NULL;
                    $exemplar_hyperlink = NULL;
                    $exemplar_rack_location = NULL;
                    $exemplar_placing_cipher = NULL;
                    foreach ($exemplar as $num => $item) {
                        $group_inv_number = (is_null($group_inv_number)) ? $item['exemplar_inventory_number'] : $group_inv_number.'.'.$item['exemplar_inventory_number'];
                        $group_exemplars_id = (is_null($group_exemplars_id)) ? $item['exemplar_id'] : $group_exemplars_id.'.'.$item['exemplar_id'];
                        $exemplarID = $item['exemplar_id'];
                        if (isset($item['exemplar_carrier']) && !empty($item['exemplar_carrier']))
                            $exemplar_carrier = $item['exemplar_carrier'];
                        if (isset($item['exemplar_hyperlink']) && !empty($item['exemplar_hyperlink']))
                            $exemplar_hyperlink = $item['exemplar_hyperlink'];
                    }
                    switch ($accessCode) {
                        case '1001':
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_hyperlink').": </th><td><a id='readonline' href='".$this->url('bookreader-viewer')."?bookID=".$this->driver->getUniqueId()."&view_mode=LQ' rel='nofollow' target='_blank'>".$this->transEsc('access_read')."</a></td></tr>";
                            break;
                        case '1002':
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_hyperlink').": </th><td><a href='".$exemplar_hyperlink."'>".$this->transEsc('access_gainAccess')."</a></td></tr>";
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access').": </th><td>".$this->translate(str_replace('%%link%%', '<a href="//opac.libfl.ru/WebReaderT/(S(ev5t1wja0rchxr20r5gnvh55))/Default.aspx" target="_blank">'.$this->transEsc('access_toRegister').'</a>', $this->transEsc($accessCode)))."</td></tr>";
                            break;
                        case '1004':
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_hyperlink').": </th><td><a href='".$exemplar_hyperlink."'>".$this->transEsc('access_gainAccess')."</a></td></tr>";
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access').": </th><td>".$this->translate(str_replace('%%link%%', '<a href="//opac.libfl.ru/WebReaderT/(S(ev5t1wja0rchxr20r5gnvh55))/Default.aspx" target="_blank">'.$this->transEsc('access_toRegister').'</a>', $this->transEsc($accessCode)))."</td></tr>";
                            echo "<tr><th style='width:160px;'>".$this->transEsc('access_additionalInfo').": </th><td><a href='//libfl.ru/static/litres' target='_blank'>".$this->transEsc('access_descriptionLitres')."</a><br/><a href='//libfl.ru/static/litres_how_to.pdf' target='_blank'>".$this->transEsc('access_instructionsForAccessing')."</a><br/><a href='https://goo.gl/EYPcrC' target='_blank'>".$this->transEsc('access_instructionsForAccessAndWorkLitres')."</a></td></tr>";
                            break;
                        case '1008':
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_hyperlink').": </th><td><a href='".$exemplar_hyperlink."'>".$this->transEsc('access_gainAccess')."</a></td></tr>";
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access').": </th><td>".$this->translate(str_replace('%%link%%', '<a href="//opac.libfl.ru/WebReaderT/(S(ev5t1wja0rchxr20r5gnvh55))/Default.aspx" target="_blank">'.$this->transEsc('access_toRegister').'</a>', $this->transEsc($accessCode)))."</td></tr>";
                            echo "<tr><th style='width:160px;'>".$this->transEsc('access_additionalInfo').": </th><td><a href='//ebooks.libfl.ru/' target='_blank'>".$this->transEsc('access_descriptionPearson')."</a><br/><a href='//ebooks.libfl.ru/' target='_blank'>".$this->transEsc('access_instructionsForAccessAndWorkPearson')."</a></td></tr>";
                            break;
                        default:
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access_unknown').": </th><td>".$this->transEsc('exemplar_access_unknown')."</td></tr>";
                    }
                    echo "<input type='hidden' name='exemplarGroupID' value='".$group_exemplars_id."' class='exemplarGroupID'>";
                    echo "<tr><td colspan='2' style='background-color: #fff!important; border-style: solid!important; border-width: 1px 0px 1px 0px!important; border-color: #b9b9b9!important; color:#0000f3; font-weight:bold;'>"
                            . "<span class='status ajax-availability hidden'>"
                            . "<span>".$this->transEsc('status_loading')."...</span>"
                            . "</span>"
                            . "</td></tr>";
                    echo '</table>';
                    echo '</div>';
                }
            endforeach;
        }

        // Печать по требованию
        if (is_array($printOnDemandAccess) && !empty($printOnDemandAccess)) {
            echo "<h2 style='margin-top: 30px;'><i class='fa fa-print' style='margin: 0px 5px 0px 0px;'></i>".$this->transEsc('access_printOnDemandAccess')."</h2>";
            foreach ($newExemplars as $access=>$exemplar):
                $accessCodes = explode('.', $access);
                $accessCode = $accessCodes[0];
                $locationCode = $accessCodes[1];
                if ($accessExemplars = array_uintersect($accessCodes, array('1009'),"strcasecmp")) {
                    echo '<div id="group_'.$access.'" class="exemplar" style="padding: 0px 0px 0px 26px;">';
                    //echo '<h3 style="font-weight:bold;"><i class="fa fa-book" style="margin: 0px 5px 0px 0px;"></i>'.$this->translate($accessCode."_group").'</h3>';
                    echo '<table class="table table-striped" summary="'.$this->transEsc('Exemplars').'" style="margin-bottom:40px;">';
                    $exemplarID = NULL;
                    $exemplar_carrier = NULl;
                    $group_inv_number = NULL;
                    $group_exemplars_id = NULL;
                    $exemplar_hyperlink = NULL;
                    $exemplar_rack_location = NULL;
                    $exemplar_placing_cipher = NULL;
                    foreach ($exemplar as $num => $item) {
                        $group_inv_number = (is_null($group_inv_number)) ? $item['exemplar_inventory_number'] : $group_inv_number.'.'.$item['exemplar_inventory_number'];
                        $group_exemplars_id = (is_null($group_exemplars_id)) ? $item['exemplar_id'] : $group_exemplars_id.'.'.$item['exemplar_id'];
                        $exemplarID = $item['exemplar_id'];
                        if (isset($item['exemplar_carrier']) && !empty($item['exemplar_carrier']))
                            $exemplar_carrier = $item['exemplar_carrier'];
                        if (isset($item['exemplar_rack_location']) && !empty($item['exemplar_rack_location']))
                            $exemplar_rack_location = $item['exemplar_rack_location'];
                        if (isset($item['exemplar_placing_cipher']) && !empty($item['exemplar_placing_cipher']))
                            $exemplar_placing_cipher = $item['exemplar_placing_cipher'];
                    }
                    switch ($accessCode) {
                        case '1009':
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_hyperlink').": </th><td><a href='".$exemplar_hyperlink."'>".$this->transEsc('access_makeRequest')."</a></td></tr>";
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access').": </th><td>".$this->translate(str_replace('%%access_LIBFL%%', '<a href="//libfl.ru/ru/item/contacts" target="_blank" >'.$this->transEsc("access_LIBFL").'</a>', $this->transEsc($accessCode)))."</td></tr>";
                            echo "<tr><th style='width:160px;'>".$this->transEsc('access_additionalInfo').": </th><td><a href='//ebooks.libfl.ru' target='_blank'>".$this->transEsc('access_descriptionPrintOnDemand')."</a></td></tr>";
                            break;
                        default:
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access_unknown').": </th><td>".$this->transEsc('exemplar_access_unknown')."</td></tr>";
                    }
                    echo "<input type='hidden' name='exemplarGroupID' value='".$group_exemplars_id."' class='exemplarGroupID'>";
                    echo "<tr><td colspan='2' style='background-color: #fff!important; border-style: solid!important; border-width: 1px 0px 1px 0px!important; border-color: #b9b9b9!important; color:#0000f3; font-weight:bold;'>"
                            . "<span class='status ajax-availability hidden'>"
                            . "<span>".$this->transEsc('status_loading')."...</span>"
                            . "</span>"
                            . "</td></tr>";
                    echo '</table>';
                    echo '</div>';
                }
            endforeach;
        }

        // Взять на дом из Библиотеки иностранной литературы
        if (is_array($takeHomeAccess) && !empty($takeHomeAccess)) {
            echo "<h2 style='margin-top: 30px;'><i class='fa fa-home' style='margin: 0px 5px 0px 0px;'></i>".$this->transEsc('access_takeHomeAccess')."</h2>";
            echo '<p style="padding: 0px 0px 0px 23px;"><a href="//libfl.ru/ru/item/contacts" target="_blank">'.$this->transEsc('access_drivingDirections').'</a>&nbsp;|&nbsp;<a href="//libfl.ru/ru/item/contacts" target="_blank">'.$this->transEsc('access_schedule').'</a></p>';
            foreach ($newExemplars as $access=>$exemplar):
                $accessCodes = explode('.', $access);
                $accessCode = $accessCodes[0];
                $locationCode = $accessCodes[1];
                if ($accessExemplars = array_uintersect($accessCodes, array('1000','1006'),"strcasecmp")) {
                    echo '<div id="group_'.$access.'" class="exemplar" style="padding: 0px 0px 0px 26px;">';
                    //echo '<h3 style="font-weight:bold;"><i class="fa fa-book" style="margin: 0px 5px 0px 0px;"></i>'.$this->translate($accessCode."_group").'</h3>';
                    echo '<table class="table table-striped" summary="'.$this->transEsc('Exemplars').'" style="margin-bottom:40px;">';
                    $exemplarID = NULL;
                    $exemplar_carrier = NULl;
                    $group_inv_number = NULL;
                    $group_exemplars_id = NULL;
                    $exemplar_hyperlink = NULL;
                    $exemplar_rack_location = NULL;
                    $exemplar_placing_cipher = NULL;
                    foreach ($exemplar as $num => $item) {
                        $group_inv_number = (is_null($group_inv_number)) ? $item['exemplar_inventory_number'] : $group_inv_number.'.'.$item['exemplar_inventory_number'];
                        $group_exemplars_id = (is_null($group_exemplars_id)) ? $item['exemplar_id'] : $group_exemplars_id.'.'.$item['exemplar_id'];
                        $exemplarID = $item['exemplar_id'];
                        if (isset($item['exemplar_carrier']) && !empty($item['exemplar_carrier']))
                            $exemplar_carrier = $item['exemplar_carrier'];
                        if (isset($item['exemplar_rack_location']) && !empty($item['exemplar_rack_location']))
                            $exemplar_rack_location = $item['exemplar_rack_location'];
                        if (isset($item['exemplar_placing_cipher']) && !empty($item['exemplar_placing_cipher']))
                            $exemplar_placing_cipher = $item['exemplar_placing_cipher'];
                    }
                    switch ($accessCode) {
                        case '1000':
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access').": </th><td>".$this->translate(str_replace('%%location_2007%%', '<a href="https://libfl.ru/ru/item/contacts" target="_blank  ">'.$this->transEsc(2007).'</a>', $this->transEsc($accessCode)))."</td></tr>";
                            echo "<tr><th style='width:160px;'>".$this->transEsc('')." </th><td>".$this->render('record/cart-buttons.phtml', ['id' => $this->driver->getUniqueId(), 'source' => $this->driver->getSourceIdentifier()])."</td></tr>";
                            echo "<tr><th style='width:160px;'>".$this->transEsc('access_additionalInfo').": </th><td><a href='http://80.250.173.142/personal/help.aspx' target='_blank'>".$this->transEsc('access_instructionsForOrderingBooksAtHome')."</a></td></tr>";
                            break;
                        case '1006':
                            echo '<tr><th style="width:160px;">'.$this->transEsc('exemplar_inventory_number').': </th>';
                            echo '<td>';
                            foreach (explode('.', $group_inv_number) as $inv_number) {
                                echo '<span class="exemplar'.$exemplarID.'" style="padding-left:7px;">'.$inv_number.'</span>';
                            }
                            echo '</td></tr>';
                            if ($locationCode == 2011) {
                                echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access').": </th><td>".$this->translate(str_replace('%%exemplar_location%%', '<a href="https://libfl.ru/ru/item/contacts" target="_blank  ">'.$this->transEsc(2007).'</a>', $this->transEsc($accessCode)))."</td></tr>";
                            } else {
                                echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access').": </th><td>".$this->translate(str_replace('%%exemplar_location%%', '<a href="https://libfl.ru/ru/item/contacts" target="_blank  ">'.$this->transEsc($locationCode).'</a>', $this->transEsc($accessCode)))."</td></tr>";
                            }
                            break;
                        default:
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access_unknown').": </th><td>".$this->transEsc('exemplar_access_unknown')."</td></tr>";
                    }
                    echo "<input type='hidden' name='exemplarGroupID' value='".$group_exemplars_id."' class='exemplarGroupID'>";
                    echo "<tr><td colspan='2' style='background-color: #fff!important; border-style: solid!important; border-width: 1px 0px 1px 0px!important; border-color: #b9b9b9!important; color:#0000f3; font-weight:bold;'>"
                            . "<span class='status ajax-availability hidden'>"
                            . "<span>".$this->transEsc('status_loading')."...</span>"
                            . "</span>"
                            . "</td></tr>";
                    echo '</table>';
                    echo '</div>';
                }
            endforeach;
        }

        // В помещении Библиотеки иностранной литературы
        if (is_array($libraryAccess) && !empty($libraryAccess)) {
            echo "<h2 style='margin-top: 30px;'><i class='fa fa-bank' style='margin: 0px 5px 0px 0px;'></i>".$this->transEsc('access_libraryAccess')."</h2>";
            echo '<p style="padding: 0px 0px 0px 23px;"><a href="//libfl.ru/ru/item/contacts" target="_blank">'.$this->transEsc('access_drivingDirections').'</a>&nbsp;|&nbsp;<a href="//libfl.ru/ru/item/contacts" target="_blank">'.$this->transEsc('access_schedule').'</a></p>';
            foreach ($newExemplars as $access=>$exemplar):
                $accessCodes = explode('.', $access);
                $accessCode = $accessCodes[0];
                $locationCode = $accessCodes[1];
                if ($accessExemplars = array_uintersect($accessCodes, array('1003','1005','1007','1011','1012','1014','1015'),"strcasecmp")) {
                    echo '<div id="group_'.$access.'" class="exemplar" style="padding: 0px 0px 0px 26px;">';
                    echo '<h3 style="font-weight:bold;"><i class="fa fa-book" style="margin: 0px 5px 0px 0px;"></i>'.$this->translate($accessCode."_group").'</h3>';
                    echo '<table class="table table-striped" summary="'.$this->transEsc('Exemplars').'" style="margin-bottom:40px;">';
                    $exemplarID = NULL;
                    $exemplar_carrier = NULl;
                    $group_inv_number = NULL;
                    $group_exemplars_id = NULL;
                    $exemplar_hyperlink = NULL;
                    $exemplar_rack_location = NULL;
                    $exemplar_placing_cipher = NULL;
                    foreach ($exemplar as $num => $item) {
                        $group_inv_number = (is_null($group_inv_number)) ? $item['exemplar_inventory_number'] : $group_inv_number.'.'.$item['exemplar_inventory_number'];
                        $group_exemplars_id = (is_null($group_exemplars_id)) ? $item['exemplar_id'] : $group_exemplars_id.'.'.$item['exemplar_id'];
                        $exemplarID = $item['exemplar_id'];
                        if (isset($item['exemplar_carrier']) && !empty($item['exemplar_carrier']))
                            $exemplar_carrier = $item['exemplar_carrier'];
                        if (isset($item['exemplar_rack_location']) && !empty($item['exemplar_rack_location']))
                            $exemplar_rack_location = $item['exemplar_rack_location'];
                        if (isset($item['exemplar_placing_cipher']) && !empty($item['exemplar_placing_cipher']))
                            $exemplar_placing_cipher = $item['exemplar_placing_cipher'];
                    }
                    switch ($accessCode) {
                        case '1003':
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_hyperlink').": </th><td><a href='".$exemplar_hyperlink."'>".$this->transEsc('access_gainAccess')."</a></td></tr>";
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access').": </th><td>".$this->transEsc($accessCode)."</td></tr>";
                            break;
                        case '1005':
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access').": </th><td>".$this->translate(str_replace('%%location_2007%%', '<a href="https://libfl.ru/ru/item/contacts" target="_blank  ">'.$this->transEsc(2007).'</a>', $this->transEsc($accessCode)))."</td></tr>";
                            echo "<tr><th style='width:160px;'></th><td>".$this->render('record/cart-buttons.phtml', ['id' => $this->driver->getUniqueId(), 'source' => $this->driver->getSourceIdentifier()])."</td></tr>";
                            echo "<tr><th style='width:160px;'>".$this->transEsc('access_additionalInfo').": </th><td><a href='http://80.250.173.142/personal/help.aspx' target='_blank'>".$this->transEsc('access_instructionsForOrderingBooksAtLibrary')."</a></td></tr>";
                            break;
                        case '1007':
                            echo '<tr><th style="width:160px;">'.$this->transEsc('exemplar_inventory_number').': </th>';
                            echo '<td>';
                            foreach (explode('.', $group_inv_number) as $inv_number) {
                                echo '<span class="exemplar'.$exemplarID.'">'.$inv_number.'</span>&nbsp;&nbsp;&nbsp;';
                            }
                            echo '</td></tr>';
                            if (!is_null($exemplar_rack_location))
                                echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_rack_location').": </th><td>".$this->transEsc($exemplar_rack_location)."</td></tr>";
                            if (!is_null($exemplar_placing_cipher))
                                echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_placing_cipher').": </th><td>".$this->transEsc($exemplar_placing_cipher)."</td></tr>";
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access').": </th><td>".$this->translate(str_replace('%%exemplar_location%%', '<a href="https://libfl.ru/ru/item/contacts" target="_blank  ">'.$this->transEsc($locationCode).'</a>', $this->transEsc($accessCode)))."</td></tr>";
                            break;
                        case '1011':
                            echo '<tr><th style="width:160px;">'.$this->transEsc('exemplar_inventory_number').': </th>';
                            echo '<td>';
                            foreach (explode('.', $group_inv_number) as $inv_number) {
                                echo '<span class="exemplar'.$exemplarID.'">'.$inv_number.'</span>&nbsp;&nbsp;&nbsp;';
                            }
                            echo '</td></tr>';
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access').": </th><td>".$this->translate(str_replace('%%exemplar_location%%', '<a href="https://libfl.ru/ru/item/contacts" target="_blank  ">'.$this->transEsc($locationCode).'</a>', $this->transEsc($accessCode)))."</td></tr>";
                            break;
                        case '1012':
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access').": </th><td>".$this->translate(str_replace('%%location_2007%%', '<a href="https://libfl.ru/ru/item/contacts" target="_blank  ">'.$this->transEsc(2007).'</a>', $this->transEsc($accessCode)))."</td></tr>";
                            echo "<tr><th style='width:160px;'>".$this->transEsc('')." </th><td>".$this->render('record/cart-buttons.phtml', ['id' => $this->driver->getUniqueId(), 'source' => $this->driver->getSourceIdentifier()])."</td></tr>";
                            echo "<tr><th style='width:160px;'>".$this->transEsc('access_additionalInfo').": </th><td><a href='http://80.250.173.142/personal/help.aspx' target='_blank'>".$this->transEsc('access_instructionsForOrderingBooksAtLibrary')."</a></td></tr>";
                            break;
                        case '1014':
                            echo '<tr><th style="width:160px;">'.$this->transEsc('exemplar_inventory_number').': </th>';
                            echo '<td>';
                            foreach (explode('.', $group_inv_number) as $inv_number) {
                                echo '<span class="exemplar'.$exemplarID.'">'.$inv_number.'</span>&nbsp;&nbsp;&nbsp;';
                            }
                            echo '</td></tr>';
                            if (!is_null($exemplar_rack_location))
                                echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_rack_location').": </th><td>".$this->transEsc($exemplar_rack_location)."</td></tr>";
                            if (!is_null($exemplar_placing_cipher))
                                echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_placing_cipher').": </th><td>".$this->transEsc($exemplar_placing_cipher)."</td></tr>";
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access').": </th><td>".$this->translate(str_replace('%%location_2007%%', '<a href="https://libfl.ru/ru/item/contacts" target="_blank  ">'.$this->transEsc(2007).'</a>', $this->transEsc($accessCode)))."</td></tr>";
                            //echo "<tr><th style='width:160px;'>".$this->transEsc('')." </th><td>".$this->render('record/cart-buttons.phtml', ['id' => $this->driver->getUniqueId(), 'source' => $this->driver->getSourceIdentifier()])."</td></tr>";
                            echo "<tr><th style='width:160px;'>".$this->transEsc('access_additionalInfo').": </th><td><a href='http://80.250.173.142/personal/help.aspx' target='_blank'>".$this->transEsc('access_instructionsForOrderingBooksAtLibrary')."</a></td></tr>";
                            break;
                        case '1015':
                            echo '<tr><th style="width:160px;">'.$this->transEsc('exemplar_inventory_number').': </th>';
                            echo '<td>';
                            foreach (explode('.', $group_inv_number) as $inv_number) {
                                echo '<span class="exemplar'.$exemplarID.'">'.$inv_number.'</span>&nbsp;&nbsp;&nbsp;';
                            }
                            echo '</td></tr>';
                            if (!is_null($exemplar_rack_location))
                                echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_rack_location').": </th><td>".$this->transEsc($exemplar_rack_location)."</td></tr>";
                            if (!is_null($exemplar_placing_cipher))
                                echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_placing_cipher').": </th><td>".$this->transEsc($exemplar_placing_cipher)."</td></tr>";
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access').": </th><td>".$this->translate(str_replace('%%location_2007%%', '<a href="https://libfl.ru/ru/item/contacts" target="_blank  ">'.$this->transEsc(2007).'</a>', $this->transEsc($accessCode)))."</td></tr>";
                            //echo "<tr><th style='width:160px;'>".$this->transEsc('')." </th><td>".$this->render('record/cart-buttons.phtml', ['id' => $this->driver->getUniqueId(), 'source' => $this->driver->getSourceIdentifier()])."</td></tr>";
                            echo "<tr><th style='width:160px;'>".$this->transEsc('access_additionalInfo').": </th><td><a href='http://80.250.173.142/personal/help.aspx' target='_blank'>".$this->transEsc('access_instructionsForOrderingBooksAtLibrary')."</a></td></tr>";
                            break;
                        default:
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access_unknown').": </th><td>".$this->transEsc('exemplar_access_unknown')."</td></tr>";
                    }
                    echo "<input type='hidden' name='exemplarGroupID' value='".$group_exemplars_id."' class='exemplarGroupID'>";
                    echo "<tr><td colspan='2' style='background-color: #fff!important; border-style: solid!important; border-width: 1px 0px 1px 0px!important; border-color: #b9b9b9!important; color:#0000f3; font-weight:bold;'>"
                            . "<span class='status ajax-availability hidden'>"
                            . "<span>".$this->transEsc('status_loading')."...</span>"
                            . "</span>"
                            . "</td></tr>";
                    echo '</table>';
                    echo '</div>';
                }
            endforeach;
        }

        // Уточнить у сотрудника
        if (is_array($askEmployeeAccess) && !empty($askEmployeeAccess)) {
            echo "<h2 style='margin-top: 30px;'><i class='fa fa-print' style='margin: 0px 5px 0px 0px;'></i>".$this->transEsc('access_askEmployeeAccess')."</h2>";
            foreach ($newExemplars as $access=>$exemplar):
                $accessCodes = explode('.', $access);
                $accessCode = $accessCodes[0];
                $locationCode = $accessCodes[1];
                if ($accessExemplars = array_uintersect($accessCodes, array('1010', '1013', '1016', '1999'),"strcasecmp")) {
                    echo '<div id="group_'.$access.'" class="exemplar" style="padding: 0px 0px 0px 26px;">';
                    //echo '<h3 style="font-weight:bold;"><i class="fa fa-book" style="margin: 0px 5px 0px 0px;"></i>'.$this->translate($accessCode."_group").'</h3>';
                    echo '<table class="table table-striped" summary="'.$this->transEsc('Exemplars').'" style="margin-bottom:40px;">';
                    $exemplarID = NULL;
                    $exemplar_carrier = NULl;
                    $group_inv_number = NULL;
                    $group_exemplars_id = NULL;
                    $exemplar_hyperlink = NULL;
                    $exemplar_rack_location = NULL;
                    $exemplar_placing_cipher = NULL;
                    foreach ($exemplar as $num => $item) {
                        $group_inv_number = (is_null($group_inv_number)) ? $item['exemplar_inventory_number'] : $group_inv_number.'.'.$item['exemplar_inventory_number'];
                        $group_exemplars_id = (is_null($group_exemplars_id)) ? $item['exemplar_id'] : $group_exemplars_id.'.'.$item['exemplar_id'];
                        $exemplarID = $item['exemplar_id'];
                        if (isset($item['exemplar_carrier']) && !empty($item['exemplar_carrier']))
                            $exemplar_carrier = $item['exemplar_carrier'];
                        if (isset($item['exemplar_rack_location']) && !empty($item['exemplar_rack_location']))
                            $exemplar_rack_location = $item['exemplar_rack_location'];
                        if (isset($item['exemplar_placing_cipher']) && !empty($item['exemplar_placing_cipher']))
                            $exemplar_placing_cipher = $item['exemplar_placing_cipher'];
                    }
                    switch ($accessCode) {
                        case '1010':
                            echo '<tr><th style="width:160px;">'.$this->transEsc('exemplar_inventory_number').': </th>';
                            echo '<td>';
                            foreach (explode('.', $group_inv_number) as $inv_number) {
                                echo '<span class="exemplar'.$exemplarID.'">'.$inv_number.'</span>&nbsp;&nbsp;&nbsp;';
                            }
                            echo '</td></tr>';
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access').": </th><td>".$this->translate(str_replace('%%exemplar_location%%', '<a href="https://libfl.ru/ru/item/contacts" target="_blank">'.$this->transEsc($locationCode).'</a>', $this->transEsc($accessCode)))."</td></tr>";
                            break;
                        case '1013':
                            echo '<tr><th style="width:160px;">'.$this->transEsc('exemplar_inventory_number').': </th>';
                            echo '<td>';
                            foreach (explode('.', $group_inv_number) as $inv_number) {
                                echo '<span class="exemplar'.$exemplarID.'">'.$inv_number.'</span>&nbsp;&nbsp;&nbsp;';
                            }
                            echo '</td></tr>';
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access').": </th><td>".$this->translate(str_replace('%%exemplar_location%%', '<a href="https://libfl.ru/ru/item/contacts" target="_blank">'.$this->transEsc($locationCode).'</a>', $this->transEsc($accessCode)))."</td></tr>";
                            break;
                        case '1016':
                            echo '<tr><th style="width:160px;">'.$this->transEsc('exemplar_inventory_number').': </th>';
                            echo '<td>';
                            foreach (explode('.', $group_inv_number) as $inv_number) {
                                echo '<span class="exemplar'.$exemplarID.'">'.$inv_number.'</span>&nbsp;&nbsp;&nbsp;';
                            }
                            echo '</td></tr>';
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access').": </th><td>".$this->translate(str_replace('%%location_2007%%', '<a href="https://libfl.ru/ru/item/contacts" target="_blank">'.$this->transEsc(2007).'</a>', $this->transEsc($accessCode)))."</td></tr>";
                            break;
                        case '1999':
                            echo '<tr><th style="width:160px;">'.$this->transEsc('exemplar_inventory_number').': </th>';
                            echo '<td>';
                            foreach (explode('.', $group_inv_number) as $inv_number) {
                                echo '<span class="exemplar'.$exemplarID.'">'.$inv_number.'</span>&nbsp;&nbsp;&nbsp;';
                            }
                            echo '</td></tr>';
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access').": </th><td>".$this->translate(str_replace('%%location_2007%%', '<a href="https://libfl.ru/ru/item/contacts" target="_blank">'.$this->transEsc(2007).'</a>', $this->transEsc($accessCode)))."</td></tr>";
                            break;
                        default:
                            echo "<tr><th style='width:160px;'>".$this->transEsc('exemplar_access_unknown').": </th><td>".$this->transEsc('exemplar_access_unknown')."</td></tr>";
                    }
                    echo "<input type='hidden' name='exemplarGroupID' value='".$group_exemplars_id."' class='exemplarGroupID'>";
                    echo '</table>';
                    echo '</div>';
                }
            endforeach;
        }
    } else {
        echo "<tr><td>" . $this->transEsc('no_exemplars') . "</td></tr>";
    }
?>
