<?php
    // Set page title.
    $this->headTitle($this->translate('Exemplars') . ': ' . $this->driver->getBreadcrumb());

    $formatter = $this->recordDataFormatter();
    $getExemplars = $formatter->getData($driver, $formatter->getDefaults('libfl_exemplar'));

    if (isset($getExemplars['Exemplar']['value']) && !empty($getExemplars['Exemplar']['value'])) {
        $getExemplarsData = json_decode(htmlspecialchars_decode($getExemplars['Exemplar']['value']));
    }

    $fields = $getExemplarsData[0];
    $exemplars = json_decode($getExemplarsData[1][0]);
    $getAccessMethod = (string) $this->driver->getMethodOfAccess()[0];
    $accessMethod = (!empty($getAccessMethod)) ? strtolower($getAccessMethod) : '';
    if (!empty($exemplars)) {
        foreach ($exemplars as $num=>$exemplar):
            echo '<div id="exemplar_'.$num.'" class=exemplar>';
            echo '<h3 style="font-weight:bold;">Экземпляр&nbsp;№&nbsp;' . $num .'</h3>';
            echo '<table class="table table-striped" summary="'.$this->transEsc('Exemplars').'" style="margin-bottom:40px;">';
            foreach ($fields as $field) {
                if (!empty($exemplar->$field)) {
                    if ($field == 'exemplar_hyperlink')
                        $exemplar->$field = "<a href='".$exemplar->$field."' target='_blank'>".$exemplar->$field."</a>";
                    if ($field == 'exemplar_inv_note') {
                        echo "<tr><th>".$this->transEsc('exemplar_inventory_number').": </th><td>".$exemplar->exemplar_inventory_number." (".$this->transEsc('exemplar_inv_note').": ".$exemplar->exemplar_inv_note.")</td></tr>";
                    }
                    echo "<tr><th style='width:25%;'>".$this->transEsc($field)."</th><td>".$this->transEsc($exemplar->$field)."</td></tr>";
                }
            }
            echo "<input type='hidden' name='exemplarID' value='".$exemplar->exemplar_id."' class='exemplarID'>";
            /*echo "<tr><td colspan='2' style='background-color: #fff!important; border-style: solid!important; border-width: 1px 0px 1px 0px!important; border-color: #b9b9b9!important; color:#0000f3; font-weight:bold;'>"
                    . "<span class='status ajax-availability hidden'>"
                    . "<span>".$this->transEsc('status_loading')."...</span>"
                    . "</span>"
                    . "<span class='access-method hidden'>&nbsp;(".$this->transEsc($accessMethod).")</span>"
                    . "</td></tr>";*/
            echo '</table>';
            echo '</div>';
        endforeach;
    } else {
        echo "<tr><td>" . $this->transEsc('no_exemplars') . "</td></tr>";
    }
?>
