<? /* Display thumbnail if appropriate: */ ?>
<? if ($cover): ?>
  <? if ($this->link): ?><a data-fancybox="covers" href="<?=$this->escapeHtmlAttr($cover)?>"><? endif; ?>
  <img alt="<?=$this->transEsc('Cover Image')?>" <? if ($linkPreview): ?>data-linkpreview="true" <? endif; ?>class="recordcover" src="<?=$this->escapeHtmlAttr($cover); ?>"/>
  <? if ($this->link): ?></a><? endif; ?>
<? else: ?>
  <img src="<?=$this->url('cover-unavailable')?>" <? if ($linkPreview): ?>data-linkpreview="true" <? endif; ?>class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
<? endif; ?>
<?php
    if ($additional_covers) {
        foreach ($additional_covers as $addCover) {
            echo "<a data-fancybox='covers' href='".$this->escapeHtmlAttr($addCover)."' style='display:none'></a>";
        }
    }
?>