<?
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  // Set up breadcrumbs:
  // $this->layout()->breadcrumbs = '<li><a href="/">Поиск</a></li>';
 print_r(  );
  if ($this->searchMemory()->getLastSearchLink($this->driver->getBreadcrumb())) {
    $this->layout()->breadcrumbs .= '<li>' . $this->searchMemory()->getLastSearchLink($this->driver->getBreadcrumb(), 'Результаты поиска: ', '</li> ');
  } else {
    $this->layout()->breadcrumbs .= '<li>' . $this->driver->getShortTitle() . '</li>';
  }

    // '<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';
  $this->layout()->title = $this->driver->getShortTitle();
?>

<? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
  <ul class="pager hidden-print">
    <? if ($this->scrollData['previousRecord']): ?>
      <? if ($this->scrollData['firstRecord']): ?>
        <li>
          <a href="<?=$this->recordLink()->getUrl($this->scrollData['firstRecord'])?>" title="<?=$this->transEsc('First Search Result')?>" rel="nofollow">&laquo; <?=$this->transEsc('First')?></a>
        </li>
      <? endif; ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['previousRecord'])?>" title="<?=$this->transEsc('Previous Search Result')?>" rel="nofollow">&laquo; <?=$this->transEsc('Prev')?></a>
      </li>
    <? else: ?>
      <? if ($this->scrollData['firstRecord']): ?>
        <li class="disabled"><a href="#">&laquo; <?=$this->transEsc('First')?></a></li>
      <? endif; ?>
      <li class="disabled"><a href="#">&laquo; <?=$this->transEsc('Prev')?></a></li>
    <? endif; ?>
    <?=$this->transEsc('of_num_results', [
      '%%position%%' => $this->localizedNumber($this->scrollData['currentPosition']),
      '%%total%%' => $this->localizedNumber($this->scrollData['resultTotal'])
    ]) ?>
    <? if ($this->scrollData['nextRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['nextRecord'])?>" title="<?=$this->transEsc('Next Search Result')?>" rel="nofollow"><?=$this->transEsc('Next')?> &raquo;</a>
      </li>
      <? if ($this->scrollData['lastRecord']): ?>
        <li>
          <a href="<?=$this->recordLink()->getUrl($this->scrollData['lastRecord'])?>" title="<?=$this->transEsc('Last Search Result')?>" rel="nofollow"><?=$this->transEsc('Last')?> &raquo;</a>
        </li>
      <? endif; ?>
     <? else: ?>
      <li class="disabled"><a href="#"><?=$this->transEsc('Next')?> &raquo;</a></li>
      <? if ($this->scrollData['lastRecord']): ?>
        <li class="disabled"><a href="#"><?=$this->transEsc('Last')?> &raquo;</a></li>
      <? endif; ?>
    <? endif; ?>
  </ul>
<? endif; ?>



<div class="record source<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>">
  <div class="mainbody">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" />
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier()) ?>" class="hiddenSource" />
    <?=$this->flashmessages()?>
    <?=$this->record($this->driver)->getCoreMetadata()?>
      <?=$this->record($this->driver)->getToolbar()?>
    <? if (count($this->tabs) > 0): ?>
      <a name="tabnav"></a>
      <div class="record-tabs">
        <ul class="nav nav-tabs">
          <? foreach ($this->tabs as $tab => $obj): ?>
            <? // add current tab to breadcrumbs if applicable:
              $desc = $obj->getDescription();
              $tab_classes = [];
              if (0 === strcasecmp($this->activeTab, $tab)) {
                if (!$this->loadInitialTabWithAjax || !$obj->supportsAjax()) {
                  $tab_classes[] = 'active';
                }
                $tab_classes[] = 'initiallyActive';
                // $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
                $this->layout()->breadcrumbs .= '<li class="active">Книга</li>';
                $activeTabObj = $obj;
              }
              if (!$obj->isVisible()) { $tab_classes[] = 'hidden'; }
              if (!$obj->supportsAjax()) { $tab_classes[] = 'noajax'; }
            ?>
            <li<?=count($tab_classes) > 0 ? ' class="' . implode(' ', $tab_classes) . '"' : ''?>>
              <a class="<?=strtolower($tab) ?>" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"<? if ($obj->supportsAjax() && in_array($tab, $this->backgroundTabs)):?> data-background<? endif ?>><?=$this->transEsc($desc)?></a>
            </li>
          <? endforeach; ?>
        </ul>

        <div class="tab-content">
          <? if (!$this->loadInitialTabWithAjax || !isset($activeTabObj) || !$activeTabObj->supportsAjax()): ?>
            <div class="tab-pane active <?=$this->activeTab ?>-tab">
              <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
            </div>
          <? endif; ?>
        </div>
      </div>
    <? endif; ?>

    <?=$this->driver->supportsCoinsOpenURL()?'<span class="Z3988" title="'.$this->escapeHtmlAttr($this->driver->getCoinsOpenURL()).'"></span>':''?>

    <div class='access_info clearfix'>
      <div class='left'>
        <span>Информация о доступе</span>
        <?php echo "<a data-lightbox href='".$this->url('sendaccess-home')."?params_access=".json_encode(array('url'=>$this->serverUrl(true)))."' rel='nofollow'>".$this->transEsc('access_print')."</a>";?><br>
        <?php echo "<a data-lightbox href='".$this->url('sendaccess-home')."?params_access=".json_encode(array('url'=>$this->serverUrl(true)))."' rel='nofollow'>".$this->transEsc('Email this')."</a>";?>
      </div>
      <div class='right'>
        <span>Сервис</span>
        <?php
            $fund = $this->driver->getFund()[0];
            $uID = $this->driver->getUniqueId();
            $pin = explode('_', $uID)[1];
            if ($fund == 5000) {
                $baza = 1;
            } else if ($fund == 5001) {
                $baza = 2;
            }
            if (in_array($fund, array('5000','5001'))) {
                echo "<a class='digitizingBook' href='//opac.libfl.ru/TurnDigBooks/default.aspx?pin=".$pin."&baza=".$baza."' target='_blank' rel='nofollow'>".$this->transEsc('digitizingBook')."</a>";
                echo "<a class='digitizingBook-disabled' style='color:grey; display:none;'>".$this->transEsc('digitizingBook')."</a>";
            } else {
                echo "<span class='digitizingBook-disabled' style='cursor:pointer;color:#787878;font-size: 12px;font-weight: bold;text-transform: uppercase;'>".$this->transEsc('digitizingBook')."</span>";
            }
        ?>
      </div>
    </div>
  </div>

  <!--<div class="<?=$this->layoutClass('sidebar')?>">
    <? foreach ($this->related()->getList($this->driver) as $current): ?>
      <?=$this->related()->render($current)?>
    <? endforeach; ?>
  </div>-->
</div>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, '$(document).ready(recordDocReady);', 'SET'); ?>
